wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.14.2
    framework: huggingface
    huggingface_version: 4.27.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683610756.572908
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      - 83
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      - 83
      3:
      - 23
      4: 3.8.16
      5: 0.14.2
      6: 4.27.1
      8:
      - 5
pretrained_model_name_or_path:
  desc: null
  value: /home/jinyujie/.cache/huggingface/hub/models--stabilityai--stable-diffusion-2-1/snapshots/36a01dc742066de2e8c91e7cf0b8f6b53ef53da1
revision:
  desc: null
  value: null
tokenizer_name:
  desc: null
  value: null
instance_data_dir:
  desc: null
  value: ./work_dirs/people_1/instance_images
class_data_dir:
  desc: null
  value: null
instance_prompt:
  desc: null
  value: a photo of cartoon man
class_prompt:
  desc: null
  value: null
validation_prompt:
  desc: null
  value: A photo of cartoon man in a house
num_validation_images:
  desc: null
  value: 4
validation_epochs:
  desc: null
  value: 50
with_prior_preservation:
  desc: null
  value: false
prior_loss_weight:
  desc: null
  value: 1.0
num_class_images:
  desc: null
  value: 100
output_dir:
  desc: null
  value: ./work_dirs/people_1/output_dir
seed:
  desc: null
  value: 0
resolution:
  desc: null
  value: 768
center_crop:
  desc: null
  value: false
train_text_encoder:
  desc: null
  value: false
train_batch_size:
  desc: null
  value: 1
sample_batch_size:
  desc: null
  value: 4
num_train_epochs:
  desc: null
  value: 125
max_train_steps:
  desc: null
  value: 500
checkpointing_steps:
  desc: null
  value: 100
checkpoints_total_limit:
  desc: null
  value: null
resume_from_checkpoint:
  desc: null
  value: null
gradient_accumulation_steps:
  desc: null
  value: 1
gradient_checkpointing:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 0.0001
scale_lr:
  desc: null
  value: false
lr_scheduler:
  desc: null
  value: constant
lr_warmup_steps:
  desc: null
  value: 0
lr_num_cycles:
  desc: null
  value: 1
lr_power:
  desc: null
  value: 1.0
dataloader_num_workers:
  desc: null
  value: 0
use_8bit_adam:
  desc: null
  value: false
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_weight_decay:
  desc: null
  value: 0.01
adam_epsilon:
  desc: null
  value: 1.0e-08
max_grad_norm:
  desc: null
  value: 1.0
push_to_hub:
  desc: null
  value: false
hub_token:
  desc: null
  value: null
hub_model_id:
  desc: null
  value: null
logging_dir:
  desc: null
  value: logs
allow_tf32:
  desc: null
  value: false
report_to:
  desc: null
  value: wandb
mixed_precision:
  desc: null
  value: null
prior_generation_precision:
  desc: null
  value: null
local_rank:
  desc: null
  value: -1
enable_xformers_memory_efficient_attention:
  desc: null
  value: false
